### ISSUE TITLE
You can’t full-screen an element of a popup

### ISSUE THREAD

**Issue by robinhouston** [kiln/flourish-popup#19]
Full-screening an element of a popup using the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) doesn’t work.

This is apparently caused by the code that removes the “constrainer“ element, to prevent it from interfering with the computation of dimensions. A solution may be to hide the element instead.

See kiln/template-3d-marker-map#58.

**Comment by timbrock** [comment]
This isn't specific to Firefox, it happens in (at least) Chrome as well.

**Comment by robinhouston** [comment]
On further investigation, I’m not sure this is really the problem at all.

I’ll close this issue for now, and reopen if it starts to look like it is after all.

**Comment by robinhouston** [comment]
Okay, this is indeed a problem with @flourish/popup! It just took me a while to catch up with @hughsk’s investigations, I think.
