### ISSUE TITLE
Column content does not get pulled through with Handlebars in panel popup

### ISSUE THREAD

**Issue by luptilu** [kiln/flourish-popup#30]
Came across this while demoing the new panel functionality to a customer yesterday:

When you try to access content from a column with curly brackets, it does not seem to pull anything through and defaults to [object] [Object].

Example:

https://app.flourish.studio/visualisation/3520848/edit

<img width="1430" alt="Screenshot 2020-08-20 at 11 04 37" src="https://user-images.githubusercontent.com/34059973/90757199-3e56aa80-e2d5-11ea-9b85-1d4bb74d19ac.png">

It seems to work fine for the popups, just not the panels (also not when only "Panel" is selected.)

**Comment by theduncanclark** [comment]
Ah, this was just an outdated version of the popup module, which @daanlouter and I fixed last week. I've republished with the correct version to fix it.
